# Docker Compose for Bible API Development
version: '3.8'

services:
  bible-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
    volumes:
      - .:/app  # Mount source code for development
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload