# Docker Compose for Bible API Development
version: '3.8'

services:
  bible-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://bible:password@db:3306/bible_api
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app  # Mount source code for development
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bible_api
      - MYSQL_USER=bible
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: