name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests with coverage + JUnit
        run: |
          mkdir -p reports
          pytest --cov=app --cov=main --cov-report=term-missing --junitxml=reports/junit.xml --maxfail=1 -q
      - name: Generate markdown test report
        run: |
          python tools/generate_test_report.py reports/junit.xml > reports/test-report.md
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
